### ISSUE TITLE
some questions about the ECB block structure diagram in the paper 

### ISSUE THREAD

**Issue by zhangliukun** [xindongzhang/ECBSR#10]
Thanks for your great work. I have some questions about the  ECB block structure diagram in the paper.
The ECB block in the paper has conv-3*3 and sobel-Dy branch but  conv-1*1 and sobel-Dy int the code. Is there someting wrong in the  structure diagram  (3.1 b) of the paper?

**Comment by xindongzhang** [comment]
> Thanks for your great work. I have some questions about the ECB block structure diagram in the paper.
> The ECB block in the paper has conv-3_3 and sobel-Dy branch but conv-1_1 and sobel-Dy int the code. Is there someting wrong in the structure diagram (3.1 b) of the paper?

Thanks for your interest to this work. It is an typo and should be conv1x1-SobelDy sequence, please refer to the implementation of ecb.py.
