### ISSUE TITLE
DLC模型转换时pixel shuffle GPU/DSP runtime不支持

### ISSUE THREAD

**Issue by liujianisme** [xindongzhang/ECBSR#16]
你好，最近我将SR模型转换为SNPE DLC模型的时候出现GPU/DSP runtime不支持pixelshuffle的问题，请教一下如何解决？
我的具体环境如下：
芯片：865
snpe版本：1.55.0
系统：aarch64_ubuntu1804_rb5

具体问题表述：将pytorch模型转换为onnx，然后将onnx模型转成dlc模型的时候，snpe会自动将pixelshuffle操作分解为reshape、permute等操作，在模型输入尺寸超过320*320的时候转换模型就会出现dsp/gpu runtime不支持的情况。

在您的论文中有提到在DSP上实现了1080p的实时超分，请问一下您有没有遇到这个问题？然后您是怎么解决的呢？
非常感谢！！！

**Comment by kyz20** [comment]
> 你好，最近我将SR模型转换为SNPE DLC模型的时候出现GPU/DSP runtime不支持pixelshuffle的问题，请教一下如何解决？ 我的具体环境如下： 芯片：865 snpe版本：1.55.0 系统：aarch64_ubuntu1804_rb5
> 
> 具体问题表述：将pytorch模型转换为onnx，然后将onnx模型转成dlc模型的时候，snpe会自动将pixelshuffle操作分解为reshape、permute等操作，在模型输入尺寸超过320*320的时候转换模型就会出现dsp/gpu runtime不支持的情况。
> 
> 在您的论文中有提到在DSP上实现了1080p的实时超分，请问一下您有没有遇到这个问题？然后您是怎么解决的呢？ 非常感谢！！！

这个和硬件相关的，输入宽高过大是不支持的，用更大倍率的pixelshuffle将宽高变得更小，最新的高通芯片可能支持更大的宽高。另外，snpe是提供tf的depth2space和space2depth的。

**Comment by xindongzhang** [comment]
> 你好，最近我将SR模型转换为SNPE DLC模型的时候出现GPU/DSP runtime不支持pixelshuffle的问题，请教一下如何解决？ 我的具体环境如下： 芯片：865 snpe版本：1.55.0 系统：aarch64_ubuntu1804_rb5
> 
> 具体问题表述：将pytorch模型转换为onnx，然后将onnx模型转成dlc模型的时候，snpe会自动将pixelshuffle操作分解为reshape、permute等操作，在模型输入尺寸超过320*320的时候转换模型就会出现dsp/gpu runtime不支持的情况。
> 
> 在您的论文中有提到在DSP上实现了1080p的实时超分，请问一下您有没有遇到这个问题？然后您是怎么解决的呢？ 非常感谢！！！

 @JimmyLauren 您好，感谢关注这个工作。关于您提到的问题，二楼也给了可以解决的方法（谢谢@kyz20 ） 。您可以尝试如下几种方案来做工程部署，

（1）模型导出可以pytorch--->tflite/pb（会显示做pixelshuffle到depth2space的op替换），项目中有convert.py文件，您可以参考一下；然后走snpe的部署流程，toolchain这个时候会parser成depth2space来做上采样。
（2）如果硬件对pixelshuffle/depth2space有限制，可以将network切成两部分，第一个sub-graph输出pixelshuffle之前的特征，第二sub-graph只进行pixelshuffle任务（CPU上很容易实现，pixelshuffle相当于数据重排，你也可以做一下内存映射来加速）；至于两个sub-graph之间怎么调度，共享内存怎么设计，这个可以根据业务的latency需求去调试。
（3）第三种方案的话，您可以采用tflite作为推理引擎，tflite支持使用hexagon dsp作为推理的delegate（需要额外编译支持hexagon的tflite相关的so文件），推理速度可以做到接近snpe的推理速度。后续cvpr结束后，我也会开源这部分的工程native代码给大家参考。
上面三种方式希望有一种能解决到您现在碰到的工程问题，关于工程部署的问题也欢迎大家来沟通交流。

**Comment by liujianisme** [comment]
@kyz20 @xindongzhang 非常感谢！！！！

**Comment by zhangliukun** [comment]
可以考虑使用反卷积替代pixelshuffle

**Comment by xindongzhang** [comment]
> 可以考虑使用反卷积替代pixelshuffle

@JimmyLauren 也可以参考一下zhangliukun的建议，也是一种解决方式，（1）可以将pixelshuffle在训练时换成convtranspose，（2）也可以将训练好的pixelshuffle用一个特殊结构的convtranspose进行等价替换（其权重为一个仅包含0和1的稀疏tensor），如果需要换成pb/tflite做deploy的话，稍微修改一下convert.py就可以。@zhangliukun 感谢建议

**Comment by JimmyLauren** [comment]
@zhangliukun @xindongzhang 感谢建议。但是我的理解是convtranspose在进行操作的时候会先插值和padding，然后再进行标准的conv操作，这样的话相当于是将特征图resize后再conv，而pixelshuffle操作不涉及插值操作，这样的话应该是没有pixelshuffle好的吧，尤其替换的pixelshuffle是在网络的最后一层。不知道我的理解对不对

**Comment by liujianisme** [comment]
@zhangliukun @xindongzhang 感谢建议。但是我的理解是convtranspose在进行操作的时候会先插值和padding，然后再进行标准的conv操作，这样的话相当于是将特征图resize后再conv，而pixelshuffle操作不涉及插值操作，这样的话应该是没有pixelshuffle好的吧，尤其替换的pixelshuffle是在网络的最后一层。不知道我的理解对不对。

**Comment by zhangliukun** [comment]
F.conv_transpose2d这个操作，没看过源码，按理说不会插值的，其可通过自定义的卷积核来实现和pixelshuffle等效的操作，效果基本一致。
