### ISSUE TITLE
merge sr Ychannel & CbCr to rgb

### ISSUE THREAD

**Issue by fangichao** [xindongzhang/ECBSR#19]
i wirte the code to merge Ychannel by sr with CbCr upsampled by bicubic, but the final rgb mat contains many blue or green or red pixels.

将超分后的Y通道和直接只用bicubic插值上采样的CbCr转换为rgb格式图片保存，发现有很多红绿蓝的像素点，怎么解决？能分享一下代码吗

**Comment by fangichao** [comment]
make sure the pixel value in [0, 255]

**Comment by zhangzheng2242** [comment]
> i wirte the code to merge Ychannel by sr with CbCr upsampled by bicubic, but the final rgb mat contains many blue or green or red pixels.
> 
> 将超分后的Y通道和直接只用bicubic插值上采样的CbCr转换为rgb格式图片保存，发现有很多红绿蓝的像素点，怎么解决？能分享一下代码吗

请问如何将生成的Y通道转为RGB图片并保存呢，就是如何保存图片呀，求大佬分享一下相关代码，不胜感激
