### ISSUE TITLE
Where is the inference moduel？

### ISSUE THREAD

**Issue by typhoonlee** [xindongzhang/ECBSR#2]
Thank you very much for your work, it is very helpful to my study!
I did not find the code for the inference where shows how to implement the re-parameterizable building during testing?

**Comment by xindongzhang** [comment]
> Thank you very much for your work, it is very helpful to my study!
> I did not find the code for the inference where shows how to implement the re-parameterizable building during testing?

Thanks for your interest to this work, the implementation details can be found on /models/ecb.py. More specifically, you can refer to the re_params function of SeqConv3x3/ECB class.

**Comment by dreamhua82** [comment]
Hi, when I try to directly use your ECB to replace common conv 3*3, the parameters and GPU consumption will increase?

**Comment by xindongzhang** [comment]
> Hi, when I try to directly use your ECB to replace common conv 3*3, the parameters and GPU consumption will increase?

Hi, thanks for your interest to this work. The parameters and GPU consumption  will increase at training phase, while it introduce no extra cost after folded back into a plain conv topology at inference phase.
