### ISSUE TITLE
About color training

### ISSUE THREAD

**Issue by mychina75** [xindongzhang/ECBSR#3]
Thank you for your work.
default colors set as 1, when I tried to train 3(RGB) image, error occurred...
maybe x need concat more times?

train the model from scratch!
##===========Epoch: 0=============##
Traceback (most recent call last):
  File "/code/ECBSR/train.py", line 143, in <module>
    sr = model(lr)
  File "/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/code/ECBSR/models/ecbsr.py", line 28, in forward
    y = self.backbone(x) + x
RuntimeError: The size of tensor a (12) must match the size of tensor b (3) at non-singleton dimension 1

**Comment by mychina75** [comment]
and... 
the scale rate is 2 now, if set scale rate as 3 or 4. we need to concat so many times 'x' to add with backbone()?
how do you think?
thank you~

**Comment by xindongzhang** [comment]
> Thank you for your work.
> default colors set as 1, when I tried to train 3(RGB) image, error occurred...
> maybe x need concat more times?
> 
> train the model from scratch!
> ##===========Epoch: 0=============##
> Traceback (most recent call last):
> File "/code/ECBSR/train.py", line 143, in
> sr = model(lr)
> File "/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/code/ECBSR/models/ecbsr.py", line 28, in forward
> y = self.backbone(x) + x
> RuntimeError: The size of tensor a (12) must match the size of tensor b (3) at non-singleton dimension 1

Hi, thanks for your interest to this work. ECBSR is trained and test on the setting which the colors=1, e.g. Y channel out of Ycbcr. If you want to extend ECBSR to RGB source, you need to take care of the data layout as I have mentioned in the README doc.

**Comment by xindongzhang** [comment]
> backbone

"nearest upsampling", "concat colors*scale*scale before addition" and "broadcast-like addition before pixel-shuffle" are doing the same things to some extent. However, the computational cost among them are quite different on mobile devices. We suggest the "broadcast-like addition before pixel-shuffle" for generality.

**Comment by xindongzhang** [comment]
> and...
> the scale rate is 2 now, if set scale rate as 3 or 4. we need to concat so many times 'x' to add with backbone()?
> how do you think?
> thank you~

"nearest upsampling", "concat colorsscalescale before addition" and "broadcast-like addition before pixel-shuffle" are doing the same things to some extent. However, the computational cost among them are quite different on mobile devices. We suggest the "broadcast-like addition before pixel-shuffle" for generality.

**Comment by xindongzhang** [comment]
"nearest upsampling", "concat <colors x scale x scale> times before addition" and "broadcast-like addition before pixel-shuffle" are doing the same things to some extent. However, the computational cost among them are quite different on mobile devices. We suggest the "broadcast-like addition before pixel-shuffle" for generality.

**Comment by xindongzhang** [comment]
> and...
> the scale rate is 2 now, if set scale rate as 3 or 4. we need to concat so many times 'x' to add with backbone()?
> how do you think?
> thank you~

"nearest upsampling", "concat N times (colors x scale x scale) before addition" and "broadcast-like addition before pixel-shuffle" are doing the same things to some extent. However, the computational cost among them are quite different on mobile devices. We suggest the "broadcast-like addition before pixel-shuffle" for generality.

**Comment by mychina75** [comment]
Nice~
I tried to train the model, the evaluation result on DIV2K_val is about 32.2x... so good.

**Comment by wxslby** [comment]
> ，"添加前的n次（颜色x比例x比例x比例）"和"像素随机播放之前的广播式添加"在某种程度上是做同样的事情。但是，它们之间的计算成本在移动设备上有很大不同。为了通用起见，我们建议使用"像素随机播放之前的广播式

Hello, I want to know how to train models with RGB pictures. I really want to train with RGB, and recover from RGB pictures, and what should I do?  Thanks!

> ‎不错~‎‎我尝试训练模型，DIV2K_val的评估结果约为32.2x...很好。‎
