### ISSUE TITLE
About pretrained model

### ISSUE THREAD

**Issue by oneTaken** [xindongzhang/ECBSR#6]
Would you provide the pretrained model?
Thx.

**Comment by xindongzhang** [comment]
> Would you provide the pretrained model?
> Thx.

Thanks for your interest to this work. They are on the schedule, we will release them after CVPR of this year.

**Comment by zhgqcn** [comment]
想去要训练好的模型+1

> Why not release the pretrained model now? Though the model can be trained after hundreds epoches, It costs to much time. If you release the pretrained model now, we can see the awesome results conveniently. Thx.
