### ISSUE TITLE
训练时loss波动异常

### ISSUE THREAD

**Issue by buptlj** [xindongzhang/ECBSR#9]
感谢作者的贡献！我正尝试训练3通道图片，目前遇到几个问题：
1、当训练ECBSR-M4C16时，训练基本正常，但是psnr比论文中低不少，我用了IMDN代码中的测试方法，将图片转成Ycbcr之后，针对Y通道计算psnr和ssim，但是测试结果在set14上psnr只有31.2x左右，在set5上psnr只有34.96左右。如果直接计算3通道图片的psnr和ssim，结果会更低。
2、当训练ECBSR-M16C64时，训练loss波动异常，loss会不定期的变得非常大：
```
##===========Epoch: 15=============##
Epoch:015, 03200/51200, loss: 4.5040, time: 35.135
Epoch:015, 06400/51200, loss: 4.3543, time: 30.960
Epoch:015, 09600/51200, loss: 4.3308, time: 30.984
Epoch:015, 12800/51200, loss: 4.3714, time: 30.946
Epoch:015, 16000/51200, loss: 4.3591, time: 31.149
Epoch:015, 19200/51200, loss: 498924.5582, time: 31.234
Epoch:015, 22400/51200, loss: 529279.5449, time: 31.021
Epoch:015, 25600/51200, loss: 463260.1697, time: 31.044
Epoch:015, 28800/51200, loss: 411850.2629, time: 30.985
Epoch:015, 32000/51200, loss: 370703.8992, time: 31.002
Epoch:015, 35200/51200, loss: 337032.6480, time: 31.208
Epoch:015, 38400/51200, loss: 308969.3531, time: 31.480
Epoch:015, 41600/51200, loss: 285220.5471, time: 31.479
Epoch:015, 44800/51200, loss: 264861.9574, time: 30.958
Epoch:015, 48000/51200, loss: 247216.6885, time: 30.925
Epoch:015, 51200/51200, loss: 231775.5556, time: 31.046
[set5-X2], PSNR/SSIM: 7.86/0.0751 (Best: 32.21/0.9010, Epoch: 14/14)
[set14-X2], PSNR/SSIM: 9.28/0.1133 (Best: 28.74/0.8311, Epoch: 14/14)

```
隔几个epoch后loss就会变得异常大，但是ECBSR-M4C16不会。其他训练参数都是默认的，训练数据是DIV2K，只修改了训练时的colors为3，然后forward里y = self.backbone(x) + x进行相应的修改。目前没看出来哪里的问题。

**Comment by xindongzhang** [comment]
> 感谢作者的贡献！我正尝试训练3通道图片，目前遇到几个问题：
> 1、当训练ECBSR-M4C16时，训练基本正常，但是psnr比论文中低不少，我用了IMDN代码中的测试方法，将图片转成Ycbcr之后，针对Y通道计算psnr和ssim，但是测试结果在set14上psnr只有31.2x左右，在set5上psnr只有34.96左右。如果直接计算3通道图片的psnr和ssim，结果会更低。
> 2、当训练ECBSR-M16C64时，训练loss波动异常，loss会不定期的变得非常大：
> 
> ```
> ##===========Epoch: 15=============##
> Epoch:015, 03200/51200, loss: 4.5040, time: 35.135
> Epoch:015, 06400/51200, loss: 4.3543, time: 30.960
> Epoch:015, 09600/51200, loss: 4.3308, time: 30.984
> Epoch:015, 12800/51200, loss: 4.3714, time: 30.946
> Epoch:015, 16000/51200, loss: 4.3591, time: 31.149
> Epoch:015, 19200/51200, loss: 498924.5582, time: 31.234
> Epoch:015, 22400/51200, loss: 529279.5449, time: 31.021
> Epoch:015, 25600/51200, loss: 463260.1697, time: 31.044
> Epoch:015, 28800/51200, loss: 411850.2629, time: 30.985
> Epoch:015, 32000/51200, loss: 370703.8992, time: 31.002
> Epoch:015, 35200/51200, loss: 337032.6480, time: 31.208
> Epoch:015, 38400/51200, loss: 308969.3531, time: 31.480
> Epoch:015, 41600/51200, loss: 285220.5471, time: 31.479
> Epoch:015, 44800/51200, loss: 264861.9574, time: 30.958
> Epoch:015, 48000/51200, loss: 247216.6885, time: 30.925
> Epoch:015, 51200/51200, loss: 231775.5556, time: 31.046
> [set5-X2], PSNR/SSIM: 7.86/0.0751 (Best: 32.21/0.9010, Epoch: 14/14)
> [set14-X2], PSNR/SSIM: 9.28/0.1133 (Best: 28.74/0.8311, Epoch: 14/14)
> ```
> 
> 隔几个epoch后loss就会变得异常大，但是ECBSR-M4C16不会。其他训练参数都是默认的，训练数据是DIV2K，只修改了训练时的colors为3，然后forward里y = self.backbone(x) + x进行相应的修改。目前没看出来哪里的问题。

你好，感谢你的关注。ECBSR是针对Y channel作为输入的小型化SR网络，最近我也看到不少朋友提到想迁移到RGB做end-to-end training的想法，这个在pytorch的layout下面需要注意颜色通道和pixelshuffle要对齐，否则会非常影响psnr/ssim indexes（若不对齐，则相当于破坏图像结构了），今年cvpr后我可能会出一个rgb通道的pytorch版本的供大家参考；另外关于loss变大的情况，可以尝试降低一下lr。

**Comment by mychina75** [comment]
只用Y通道算出来的PSNR和全通道的结果还是差异比较大的。
个人理解不应该使用Y通道的评估结果作为模型的结果。
期待作者的RGB版本。
谢谢！

**Comment by xindongzhang** [comment]
> 只用Y通道算出来的PSNR和全通道的结果还是差异比较大的。
> 个人理解不应该使用Y通道的评估结果作为模型的结果。
> 期待作者的RGB版本。
> 谢谢！

谢谢回复。关于是否选取Y和RGB，最主要的一点是为了与前人的工作和评判准则保持一致。如果是工业界里使用的话，相对就比较灵活啦，一般都是兼容自己的应用或者render的pipeline。

**Comment by buptlj** [comment]
@xindongzhang 你好，我用代码里的ecbsr_x2_m4c16_prelu.yml配置，color也设置的1，训练数据是div2k。就是完全按照原始代码和配置训练，训练完后在set5上psnr 35.1左右，在set14上psnr 31.3左右，和论文中结果差距很大。想问下怎么设置可以完全复现论文中的结果。

**Comment by xindongzhang** [comment]
> @xindongzhang 你好，我用代码里的ecbsr_x2_m4c16_prelu.yml配置，color也设置的1，训练数据是div2k。就是完全按照原始代码和配置训练，训练完后在set5上psnr 35.1左右，在set14上psnr 31.3左右，和论文中结果差距很大。想问下怎么设置可以完全复现论文中的结果。

你好，谢谢回复，之前你调整过代码，是否存在版本冲突？还麻烦提供一下完整的训练log文件。

**Comment by buptlj** [comment]
> > @xindongzhang 你好，我用代码里的ecbsr_x2_m4c16_prelu.yml配置，color也设置的1，训练数据是div2k。就是完全按照原始代码和配置训练，训练完后在set5上psnr 35.1左右，在set14上psnr 31.3左右，和论文中结果差距很大。想问下怎么设置可以完全复现论文中的结果。
> 
> 你好，谢谢回复，之前你调整过代码，是否存在版本冲突呢（可以git diff看看）？还麻烦你重新clone一下项目，再训练提供一下完整的训练log文件。

我训练之前git diff了，之前修改代码是因为设置的color 3，这次用的代码里的默认配置，就把forward里改回去了，diff看了，就是数据路径不一样，下面是训练log。
[log.txt](https://github.com/xindongzhang/ECBSR/files/7233189/log.txt)

**Comment by xindongzhang** [comment]
> > > @xindongzhang 你好，我用代码里的ecbsr_x2_m4c16_prelu.yml配置，color也设置的1，训练数据是div2k。就是完全按照原始代码和配置训练，训练完后在set5上psnr 35.1左右，在set14上psnr 31.3左右，和论文中结果差距很大。想问下怎么设置可以完全复现论文中的结果。
> > 
> > 
> > 你好，谢谢回复，之前你调整过代码，是否存在版本冲突呢（可以git diff看看）？还麻烦你重新clone一下项目，再训练提供一下完整的训练log文件。
> 
> 我训练之前git diff了，之前修改代码是因为设置的color 3，这次用的代码里的默认配置，就把forward里改回去了，diff看了，就是数据路径不一样，下面是训练log。
> [log.txt](https://github.com/xindongzhang/ECBSR/files/7233189/log.txt)

收到，谢谢。麻烦你再重新clone一下代码，训练前10个epoches我看看呢。从你提供的log上面看，第一个epoch开始测试的结果就不太正常，应该还是动了测试或者其他的代码。

**Comment by xindongzhang** [comment]
提问的朋友已定位到问题，故先close掉issue。

**Comment by Feynman1999** [comment]
> 

请问您当时排查到的是什么问题呢
